version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    environment:
      - DOCKER=True
    volumes:
      - .:/rew_project
    ports:
      - "8080:8080"
    depends_on:
      - db